name: Create the PDFs

on:
  push:
    paths:
      - 'docs/**'
      - .github/workflows/create_pdfs.yaml
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install libfontconfig1-dev
        run: sudo apt install -qq libfontconfig1-dev

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install devtools
        run: install.packages("remotes")
        shell: Rscript {0}

      - name: Install mkdocs2md
        run: remotes::install_github("richelbilderbeek/mkdocs2md")
        shell: Rscript {0}

      - name: Delete PDFs
        run: |
          rm docs/pdfs/*.pdf
          ls docs/pdfs/*.pdf

      - name: Create PDFs
        run: |
          cd docs/scripts
          ./create_exercises_cover.sh
          ./create_theory_cover.sh
          ./create_exercises_book.sh
          ./create_theory_book.sh
          ls docs/pdfs/*.pdf
